version: '3.1'
services:
  consul:
    image: consul:1.15.4
    container_name: "consul"
    restart: always
    ports:
      - "8500:8500"
    volumes:
      - ./data:/consul/data
    command: [agent,-server,-ui,-client=0.0.0.0,-bootstrap-expect=1]