version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php7.3/src/project/public:/var/www/html/public
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
  php:
    image: php:7.3-fpm
    volumes:
    - ./php7.3/src/project:/var/www/html
    - ./php7.3/logs:/var/log/php